name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  node-test:
    name: Test & QA
    uses: curium-rocks/flows/.github/workflows/npm-lint-and-validate.yml@main
  node-docs:
    needs:
      - node-test
    permissions:
      contents: read
      pages: write
      deployments: write
    name: 'Docs'
    uses: curium-rocks/flows/.github/workflows/npm-publish-docs.yml@main
    with:
      publish: false
